name: Reusable Release

on:
  workflow_call:
    inputs:
      artifact_pattern:
        description: 'Pattern to find the artifacts from build jobs (e.g. package-name-*)'
        required: true
        type: string
      release_file_pattern:
        description: 'Pattern for files to include in the release (e.g. *.ipk)'
        required: false
        type: string
        default: '*.ipk'
      tag_name:
        required: true
        type: string
    secrets:
      RELEASE_TOKEN:
        required: true

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v6
        with:
          pattern: ${{ inputs.artifact_pattern }}
          path: ${{ github.workspace }}/release-assets/
          merge-multiple: true
          
      - name: List Files (Debug)
        run: ls -R ${{ github.workspace }}/release-assets/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag_name }}
          files: ${{ github.workspace }}/release-assets/${{ inputs.release_file_pattern }}
          generate_release_notes: true
          token: ${{ secrets.RELEASE_TOKEN }}
