name: OpenWrt Build Package

on:
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
      sdk_packages:
        required: true
        type: string
      artifacts_patterns:
        required: true
        type: string
      openwrt_version:
        required: true
        type: string
      openwrt_build_version:
        required: true
        type: string
      arch:
        required: true
        type: string
      target:
        required: false
        type: string
      selected_version:
        required: false
        type: string
        default: 'both'
      free_disk_space:
        required: false
        type: boolean
        default: false
      verbose:
        required: false
        type: boolean
        default: false
    outputs:
      tag_name:
        value: ${{ jobs.build.outputs.tag_name }}

jobs:
  build:
    name: Build ${{ inputs.openwrt_version }} - ${{ inputs.arch }}
    runs-on: ubuntu-latest
    if: |
      inputs.selected_version == 'both' ||
      inputs.selected_version == inputs.openwrt_version
    outputs:
      tag_name: ${{ steps.version_logic.outputs.version_tag }}

    steps:
      - name: Checkout Source
        uses: actions/checkout@v5
        with:
          path: ${{ github.workspace }}/feed/${{ inputs.package_name }}
          fetch-depth: 0

      - name: Get Version from Tag
        id: get_tag_version
        if: startsWith(github.ref, 'refs/tags/')
        uses: ChrSchu90/GitTagSemanticVersion@v1.1
        continue-on-error: true

      - name: Get Version from Makefile (Fallback)
        id: get_makefile_version
        if: always() && steps.get_tag_version.outcome != 'success'
        run: |
          MAKEFILE_PATH="${{ github.workspace }}/feed/${{ inputs.package_name }}/Makefile"
          if [ -f "$MAKEFILE_PATH" ]; then
            VERSION=$(grep "PKG_VERSION:=" "$MAKEFILE_PATH" | cut -d'=' -f2 | tr -d ' "')
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "found=true" >> $GITHUB_OUTPUT
          else
            echo "found=false" >> $GITHUB_OUTPUT
          fi

      - name: Finalize Version String
        id: version_logic
        run: |
          if [ "${{ steps.get_tag_version.outcome }}" == "success" ]; then
            FINAL_VER="${{ steps.get_tag_version.outputs.version }}"
          elif [ "${{ steps.get_makefile_version.outputs.found }}" == "true" ]; then
            FINAL_VER="${{ steps.get_makefile_version.outputs.version }}-test"
          else
            FINAL_VER="0.0.0-unknown"
          fi
          echo "version=$FINAL_VER" >> $GITHUB_OUTPUT
          echo "version_tag=v$FINAL_VER" >> $GITHUB_OUTPUT

      - name: Free Disk Space
        if: ${{ inputs.free_disk_space }}
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true

      - name: Initialize SDK Directories
        run: |
          mkdir -p ${{ github.workspace }}/artifacts
          mkdir -p ${{ github.workspace }}/feed

      - name: Build with OpenWrt SDK
        uses: Zerogiven/gh-action-sdk@main
        if: always() && inputs.target != ''
        env:
          ARCH: ${{ inputs.arch }}-${{ inputs.openwrt_build_version }}
          TARGET: ${{ inputs.target }}
          PACKAGES: ${{ inputs.sdk_packages }}
          V: ${{ inputs.verbose && 'sc' || '0' }}
          FEED_DIR: ${{ github.workspace }}/feed
          ARTIFACTS_DIR: ${{ github.workspace }}/artifacts

      - name: Build with OpenWrt SDK
        uses: Zerogiven/gh-action-sdk@main
        if: always() && inputs.target == ''
        env:
          ARCH: ${{ inputs.arch }}-${{ inputs.openwrt_build_version }}
          PACKAGES: ${{ inputs.sdk_packages }}
          V: ${{ inputs.verbose && 'sc' || '0' }}
          FEED_DIR: ${{ github.workspace }}/feed
          ARTIFACTS_DIR: ${{ github.workspace }}/artifacts

      - name: Debug
        run: |
          ls -la /home/runner/work/quectel-rm520n-thermal/quectel-rm520n-thermal/artifacts/bin/
          ls -la /home/runner/work/quectel-rm520n-thermal/quectel-rm520n-thermal/artifacts/bin/targets/

      - name: Collect and Filter Artifacts
        id: collect
        run: |
          mkdir -p ${{ github.workspace }}/filtered-assets
          
          MAIN_TARGET=$(echo "${{ inputs.arch }}" | cut -d'-' -f1)

          echo "${{ inputs.artifacts_patterns }}" | while read -r pattern; do
            [ -z "$pattern" ] && continue
            echo "üîç Searching for: $pattern"
            
            find ${{ github.workspace }}/artifacts/bin/ -name "$pattern" -type f | while read -r src; do
              FILENAME=$(basename "$src")
              
              # if [[ "${{ inputs.arch }}" == *"-"* ]]; then
              #   if [[ "$src" == *"targets/"* ]] && [[ "$src" != *"$MAIN_TARGET"* ]]; then
              #     echo "‚ö†Ô∏è Skipping mismatching target path: $src"
              #     continue
              #   fi
              # fi

              if [[ "$src" == *"targets/"* ]]; then
                T_INFO=$(echo "$src" | awk -F'/targets/' '{print $2}' | cut -d'/' -f1,2 | tr '/' '_')
                NEW_NAME="${FILENAME%.ipk}_${T_INFO}.ipk"
              else
                NEW_NAME="${FILENAME%.ipk}_${{ inputs.arch }}.ipk"
              fi

              echo "üì¶ Copying: $FILENAME"
              echo "‚û°Ô∏è Destination: $NEW_NAME"
              cp -v "$src" "${{ github.workspace }}/filtered-assets/$NEW_NAME"
            done
          done

      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ inputs.package_name }}-${{ steps.version_logic.outputs.version }}-${{ inputs.openwrt_version }}-${{ inputs.arch }}
          path: ${{ github.workspace }}/filtered-assets/*.ipk
          retention-days: 7
